liip_imagine:
  filter_sets:
    thumb:
      quality: 75
      filters:
        thumbnail:
          size: [360,200]
          mode: outbond
    medium:
      quality: 75
      filters:
        thumbnail:
          size: [250,150]
          mode: outbond